// popup.js
document.addEventListener("DOMContentLoaded", () => {
	const composer = document.getElementById("composer");
	const saveBtn = document.getElementById("save");
	const testBtn = document.getElementById("test");
	const successMessage = document.getElementById("success-message");
	const form = document.getElementById("popup-form");
	const extensionStatus = document.getElementById("extension-status");
	const extensionText = document.getElementById("extension-text");
	const awsStatus = document.getElementById("aws-status");
	const awsText = document.getElementById("aws-text");

	// Load saved settings
	chrome.storage.sync.get(["composer"], (res) => {
		composer.value = res.composer || "gmail";
	});

	// Check if we're on AWS console
	chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
		if (
			tabs[0] &&
			tabs[0].url &&
			(tabs[0].url.includes("console.aws.amazon.com") ||
				tabs[0].url.includes("lightsail.aws.amazon.com"))
		) {
			const service = tabs[0].url.includes("lightsail")
				? "lightsail"
				: "ec2";
			awsStatus.classList.remove("inactive");
			awsText.textContent = `AWS ${service} Detected`;

			// Try to get share button count
			chrome.tabs.sendMessage(
				tabs[0].id,
				{ action: "get-button-count" },
				(response) => {
					if (response && response.count > 0) {
						awsText.textContent = `${response.count} instance${
							response.count !== 1 ? "s" : ""
						} found`;
					}
				}
			);
		} else {
			awsStatus.classList.add("inactive");
			awsText.textContent = "Not on AWS Console";
		}
	});

	// Show success message
	function showSuccessMessage(message = "Settings saved!") {
		successMessage.querySelector("span:last-child").textContent = message;
		successMessage.style.display = "flex";
		setTimeout(() => {
			successMessage.style.display = "none";
		}, 2000);
	}

	// Test email function - opens compose window without recipients
	testBtn.addEventListener("click", () => {
		const subject = "🧪 AWS Instance Share - Test Email";
		const body = `═══════════════════════════════════════════════════════════════
🚀 AWS INSTANCE SHARE - TEST EMAIL
═══════════════════════════════════════════════════════════════
📅 Generated: ${new Date().toLocaleString()}

🧪 TEST CONFIGURATION
─────────────────────────────────────────────────────────────────
✅ Extension: AWS Instance Share
✅ Email Client: ${composer.options[composer.selectedIndex].text}
✅ Category: ${composer.options[composer.selectedIndex].parentElement.label}

📋 SAMPLE INSTANCE DETAILS
─────────────────────────────────────────────────────────────────
🏢 Account ID: 123456789012
🌍 Region: US East (N. Virginia) (us-east-1)
💻 Instance ID: i-0abcd1234efgh5678
📝 Name: web-server-prod-01
⚙️ Instance Type: t3.medium
🔄 State: RUNNING
📍 Availability Zone: us-east-1a

🌐 NETWORK CONFIGURATION
─────────────────────────────────────────────────────────────────
🌍 Public IPv4: 54.123.45.67
🏠 Private IPv4: 10.0.1.100
🔗 VPC ID: vpc-12345678

🔒 SECURITY CONFIGURATION
─────────────────────────────────────────────────────────────────
🛡️ Security Groups: sg-12345678, sg-87654321

💻 RESOURCE SPECIFICATIONS
─────────────────────────────────────────────────────────────────
🔧 vCPUs: 2
🧠 Memory (RAM): 4 GB
🌐 Network Performance: Up to 5 Gigabit

🔗 QUICK ACCESS
─────────────────────────────────────────────────────────────────
🖥️ Console: https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#Instances:instanceId=i-0abcd1234efgh5678
🌐 SSH Access: ssh -i your-key.pem ec2-user@54.123.45.67

═══════════════════════════════════════════════════════════════
📝 This is a test email generated by AWS Instance Share Extension
⚠️ No actual instance data was accessed for this test
═══════════════════════════════════════════════════════════════`;

		// Use same logic as content script for consistent behavior
		const composerValue = composer.value;
		const sub = encodeURIComponent(subject);
		const b = encodeURIComponent(body);

		let url = "";

		switch (composerValue) {
			// Web Clients
			case "gmail":
				url = `https://mail.google.com/mail/?view=cm&su=${sub}&body=${b}`;
				break;
			case "outlook":
				url = `https://outlook.live.com/mail/0/deeplink/compose?subject=${sub}&body=${b}`;
				break;
			case "yahoo":
				url = `https://compose.mail.yahoo.com/?subject=${sub}&body=${b}`;
				break;
			case "protonmail":
				url = `https://mail.proton.me/compose?subject=${sub}&body=${b}`;
				break;
			case "aol":
				url = `https://mail.aol.com/webmail-std/en-us/suite#compose?subject=${sub}&body=${b}`;
				break;
			case "icloud":
				url = `https://www.icloud.com/mail/#compose?subject=${sub}&body=${b}`;
				break;
			// Desktop Applications (all use mailto for system integration)
			case "thunderbird":
			case "outlook-office":
			case "apple-mail":
			case "evolution":
			case "kmail":
			case "mailto":
			default:
				url = `mailto:?subject=${sub}&body=${b}`;
				break;
		}

		try {
			window.open(url, "_blank");
			showSuccessMessage("Test email opened!");
		} catch (error) {
			console.error("Test email failed:", error);
			showSuccessMessage("Error opening test email");
		}
	});

	// Form submission
	form.addEventListener("submit", (e) => {
		e.preventDefault();

		const comp = composer.value;

		// Save settings
		chrome.storage.sync.set(
			{
				composer: comp,
			},
			() => {
				// Update button state
				const originalText = saveBtn.innerHTML;
				saveBtn.innerHTML = "✅ Saved!";
				saveBtn.disabled = true;

				showSuccessMessage();

				setTimeout(() => {
					saveBtn.innerHTML = originalText;
					saveBtn.disabled = false;
				}, 1500);
			}
		);
	});
});
